"""add stock quantity to products

Revision ID: e36cc64e19fc
Revises: ef86d57c2cc5
Create Date: 2026-09-27 20:36:51.136256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36cc64e19fc'
down_revision: Union[str, Sequence[str], None] = 'ef86d57c2cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###
