"""add attachment fields to requests

Revision ID: ef86d57c2cc5
Revises: fb131cf1ed65
Create Date: 2026-08-05 13:06:49.801931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef86d57c2cc5'
down_revision: Union[str, Sequence[str], None] = 'fb131cf1ed65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('requests', sa.Column('attachment_data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'attachment_data')
    op.drop_column('requests', 'attachment_name')
    # ### end Alembic commands ###
